---
apiVersion: v1
kind: Service
metadata:
  name: flask-server-svc
spec:
  type: NodePort
  ports:
    - name: http-flask-server
      port: 5000
      targetPort: http-mn-server
  selector:
    app: flask-server
    tier: flask-server